---
openapi: 3.0.0
info:
  title: Система аутентификации
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/98QLOKER/auth/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Аутентификация
paths:
  /auth:
    post:
      tags:
      - Аутентификация
      summary: Аутентификация пользователя
      operationId: authenticateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
            example:
              username: "79000000000"
              password: 123abc
        required: true
      responses:
        "200":
          description: Данные успешно отправлены в backend
          content:
            application/json:
              example:
                message: Успешная отправка
        "404":
          description: Пользователь не найден
          content:
            application/json:
              example:
                error: Пользователь не найден
components:
  schemas:
    AuthRequest:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
          description: Номер телефона пользователя
          format: phone-number
        password:
          type: string
          description: Пароль пользователя
